### ISSUE TITLE
Create View to show a list of sitters

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#16]
[App style guidelines](https://github.com/ios-course/ironfoudation-team-project/wiki/App-style-guidelines)

[Miro scheme with app flow](https://miro.com/app/board/uXjVMSQsET8=/?share_link_id=41046125128)

## Description

A new SwiftUI TabView needs to be created for the Pet Owner app. This TabView will display a list of sitters available for pet owners. Each row of the list should include the information described in the requirements. The list will be filled in with mocked data.

## Requirements

- A new SwiftUI TabView is created for the Pet Owner app.
- The TabView should display a list of sitters available for pet owners.
- Each list row should include an avatar, name + surname, price, and rating.
- The list of Pet sitters should be the starter tab view.
- You can use the suggested UI or choose your own, but it should follow the [App Style Guidelines](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines)

### Subtasks

- [x] Create a ViewModel for the row + tests (if needed),
- [ ] Create a ViewModel for the View + tests (if needed),
- [x] Create a View for the row,
- [ ] Create a View for the list.

#### UI Example
<img width="269" alt="Screenshot 2023-04-29 at 13 43 11" src="https://user-images.githubusercontent.com/32869814/235296228-70b46321-4bfb-4e93-bcdb-46712d30852a.png">

#### Additional details:
The Search of Sitters View is a part of the main tab screen.
