### ISSUE TITLE
Integrate obfuscator

### ISSUE THREAD

**Issue by kirpichonok** [ios-course/ironfoudation-team-project#200]
## This task is part of
#124 

## Description
Add capability to obfuscate API key in the project. The API key must not be stored in source code files of the project and be inserted at compile time. 

## Subtasks
- [x] Add a script that accepts a string and returns an obfuscated string as a sequence of integer numbers.
- [x] Add to the project a method to reveal obfuscated key.
- [ ] Add a script that reads obfuscated key from the external file and write that to the variable `key` in the source code file during build phase.
