### ISSUE TITLE
Add walkings view as a part of main tab view

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [ios-course/ironfoudation-team-project#33]
## Description:
The goal of this task is to create a view with future, active and finished walkings for pet(s). 

## To discuss:
 - clarify the DoD.

## Subtasks:

- [ ] Create the general view, that contains 3 sections with walkings: future, active, finished
- [ ] Create an active walking view section.
- [ ] Create a future (scheduled) walking view section.
- [ ] Create a finished walking view section.
